version: '3'
services:
  connector-test:
    build: ./opencti-suricata
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Suricata 
      - CONNECTOR_SCOPE=suricata # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - SURICATA_INTERVAL=2
      - SURICATA_DIR_LOGS=ChangeMe
    restart: always
